language: php

php:
- 7.0
- hhvm
- nightly

services:
  - mysql

before_script:
  - mysql -e 'create database tsr;'
  - mysql -uroot tsr < resources/tsr_2016-02-24.sql
  - cp config.sample.php config.php
  - composer install

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true